#Sample Ansible Playbook

- 
  name: Print average marks
  hosts: localhost
  vars: 
    marks: 
      - 10
      - 20
      - 30
      - 40
  tasks:
     - debug:
         msg: '{{ marks | average }}'