---
- name: Deploy a web application
  hosts: db_and_web_server1, db_and_web_server2

  tasks: 
    - name: Install all required dependencies
      apt: name={{ item }} state=installed
      with_items:
        - python
        - python-setuptools
        - python-dev
        - build-essentials
        - python-pip
    
    - include: tasks/deploy_db.yml
    - include: tasks/deploy_web.yml
    



